### ISSUE TITLE
Class Numbers are not correct STD 6 Mal

### ISSUE THREAD

**Issue by rtharayil** [Vidhyalayam/vidhyalayam.github.io#107]
1. 1. Class numbers are not correct for example classes are 1 ,2 ,2,2,3,3 ....
2. Correct the order to 1 ,2,3,4,5,6... based on the date published 
3. Also do we need Mal 1 and mal 2 for STD 6

https://vidhyalayam.online//Six/Malayalam.html

**Comment by AdvaitPai908** [comment]
There are no class 4&5 in malayalam
