### ISSUE TITLE
malayalam class 8 in Std 2

### ISSUE THREAD

**Issue by AdvaitPai908** [Vidhyalayam/vidhyalayam.github.io#224]
There are 2 class 8 in 2 Std and the 2nd class 8 date is after class 9 should i keep it before or after 9?

**Comment by CiniVincent** [comment]
with regards to Standard 2 Malayalam
class 07  on July 3rd
class 08 on July 8th
again class 08 on July 14th
class 09 on July 10
then class 11 on July 17th
also class 10 missing there

From this we can assume class 8 done on July 14th may be class10

Please change accordingly.  We are contacting teachers to check this type of errors,  probably will get their help from next week.
