### ISSUE TITLE
Standard 6

### ISSUE THREAD

**Issue by CiniVincent** [Vidhyalayam/vidhyalayam.github.io#227]
In standard 6 youtube shows 50 classes, but only 46 classes uploaded in our site.  Kindly cross check it.  Also Information technology subject is missing.

**Comment by AdvaitPai908** [comment]
Yes i havent updated it. They are new classes

**Comment by rtharayil** [comment]
STD 47 classes are in our portal

**Comment by rtharayil** [comment]
looks like we are missing a few here
